// 카테고리별 음식/식단 데이터 (참고용 큐레이션 데이터입니다. 실제 처방/식이요법은 반드시 전문의·영양사와 상담하세요)

const CATEGORIES = {
  kidney: {
    label: "신장",
    icon: "heart",
    intro: "신장에 좋은 음식인지 확인해보세요",
    note: "신장 관리 단계에 따라 권장 사항이 다를 수 있습니다.",
    foods: [
      { name: "백미밥", status: "good", desc: "칼륨·인 함량이 낮아 신장 질환자에게 무난한 주식입니다." },
      { name: "흰살생선", status: "good", desc: "가자미, 대구 등은 단백질을 적당히 공급하면서 칼륨 부담이 적습니다." },
      { name: "달걀흰자", status: "good", desc: "인 함량이 낮은 고품질 단백질원으로 노른자보다 부담이 적습니다." },
      { name: "양배추", status: "good", desc: "칼륨 함량이 낮은 채소로 데쳐서 섭취하면 더욱 좋습니다." },
      { name: "오이", status: "good", desc: "수분이 많고 칼륨 함량이 비교적 낮은 편입니다." },
      { name: "콜리플라워", status: "good", desc: "칼륨과 인이 낮아 신장식에 자주 활용되는 채소입니다." },
      { name: "무", status: "good", desc: "칼륨 함량이 낮고 소화가 잘 되는 채소입니다." },
      { name: "사과", status: "good", desc: "칼륨 함량이 비교적 낮은 과일로 껍질을 벗겨 먹으면 더 좋습니다." },
      { name: "파인애플", status: "good", desc: "다른 열대과일에 비해 칼륨이 낮은 편입니다." },
      { name: "포도", status: "good", desc: "적당량 섭취 시 칼륨 부담이 크지 않은 과일입니다." },
      { name: "두부", status: "good", desc: "적당량의 식물성 단백질원이나 1회 섭취량 조절이 필요합니다." },
      { name: "올리브오일", status: "good", desc: "칼륨·인·나트륨이 없는 지방으로 조리에 활용하기 좋습니다." },
      { name: "마늘", status: "good", desc: "향신료로 사용 시 나트륨 섭취를 줄이는 데 도움이 됩니다." },
      { name: "양파", status: "good", desc: "칼륨 함량이 비교적 낮은 향신 채소입니다." },
      { name: "식빵", status: "good", desc: "통곡물빵보다 인·칼륨 함량이 낮아 무난한 편입니다." },
      { name: "딸기", status: "good", desc: "칼륨 함량이 비교적 낮은 과일입니다." },
      { name: "배", status: "good", desc: "칼륨 함량이 낮은 편의 과일입니다." },
      { name: "자두", status: "good", desc: "다른 과일에 비해 칼륨 함량이 비교적 낮습니다." },
      { name: "감자", status: "caution", desc: "칼륨 함량이 높아 물에 데치거나 담가 칼륨을 줄인 후 섭취해야 합니다." },
      { name: "고구마", status: "caution", desc: "칼륨이 많아 섭취량을 제한하는 것이 좋습니다." },
      { name: "토마토", status: "caution", desc: "칼륨 함량이 높은 편이라 소량만 섭취하는 것이 안전합니다." },
      { name: "바나나", status: "caution", desc: "대표적인 고칼륨 과일로 신장 질환자는 섭취를 제한해야 합니다." },
      { name: "아보카도", status: "caution", desc: "칼륨과 지방이 많아 소량만 섭취해야 합니다." },
      { name: "우유", status: "caution", desc: "인과 칼륨이 많아 섭취량 조절이 필요합니다." },
      { name: "요거트", status: "caution", desc: "유제품으로 인 함량이 높은 편이라 적당량만 섭취하세요." },
      { name: "현미", status: "caution", desc: "백미보다 인·칼륨 함량이 높아 섭취량 조절이 필요합니다." },
      { name: "견과류", status: "caution", desc: "인과 칼륨이 높아 소량만 간식으로 섭취해야 합니다." },
      { name: "오렌지", status: "caution", desc: "칼륨 함량이 높은 편의 과일입니다." },
      { name: "시금치", status: "caution", desc: "칼륨이 매우 높아 데쳐서 소량만 섭취해야 합니다." },
      { name: "콩류", status: "caution", desc: "인과 칼륨이 많아 섭취량 제한이 필요합니다." },
      { name: "멜론", status: "caution", desc: "칼륨 함량이 높은 과일 중 하나입니다." },
      { name: "수박", status: "caution", desc: "수분은 많지만 칼륨 함량이 높아 섭취량을 제한해야 합니다." },
      { name: "복숭아", status: "caution", desc: "칼륨 함량이 있어 적당량만 섭취하는 것이 좋습니다." },
      { name: "감", status: "caution", desc: "당분과 칼륨이 있어 적당량만 섭취하세요." },
      { name: "키위", status: "caution", desc: "칼륨 함량이 높은 편이라 섭취량을 제한해야 합니다." },
      { name: "체리", status: "caution", desc: "칼륨이 있어 적당량만 섭취하는 것이 좋습니다." },
      { name: "버섯", status: "caution", desc: "칼륨과 인 함량이 있어 적당량만 섭취하세요." },
      { name: "콩나물", status: "caution", desc: "칼륨 함량이 있어 데쳐서 적당량만 섭취해야 합니다." },
      { name: "소고기", status: "caution", desc: "단백질과 인 함량이 있어 1회 섭취량 조절이 필요합니다." },
      { name: "돼지고기", status: "caution", desc: "단백질과 인 함량이 있어 섭취량 조절이 필요합니다." },
      { name: "참치", status: "caution", desc: "단백질원이지만 통조림 제품은 나트륨이 있어 적당량만 섭취하세요." },
      { name: "짠 국물", status: "bad", desc: "나트륨 섭취가 과도해져 신장에 부담을 줄 수 있습니다." },
      { name: "젓갈", status: "bad", desc: "염분과 인 함량이 매우 높아 피해야 합니다." },
      { name: "라면", status: "bad", desc: "나트륨과 인 함량이 높은 가공식품으로 신장에 부담을 줍니다." },
      { name: "가공육", status: "bad", desc: "햄, 소시지 등은 나트륨·인 첨가물이 많아 피해야 합니다." },
      { name: "사골국", status: "bad", desc: "인과 칼륨이 농축되어 있어 신장 질환자에게 좋지 않습니다." },
      { name: "장아찌", status: "bad", desc: "염분이 매우 높은 저장식품으로 섭취를 피해야 합니다." },
      { name: "김치", status: "bad", desc: "나트륨 함량이 높은 저장식품으로 섭취를 제한해야 합니다." },
      { name: "된장", status: "bad", desc: "나트륨 함량이 매우 높은 발효 조미료로 소량만 사용하세요." },
      { name: "귤", status: "caution", desc: "칼륨 함량이 있어 적당량만 섭취하세요." },
      { name: "망고", status: "caution", desc: "칼륨 함량이 있어 적당량만 섭취하세요." },
      { name: "석류", status: "caution", desc: "칼륨 함량이 있어 적당량만 섭취하세요." },
      { name: "자몽", status: "caution", desc: "칼륨 함량이 있어 적당량만 섭취하세요." },
      { name: "살구", status: "caution", desc: "칼륨 함량이 있어 적당량만 섭취하세요." },
      { name: "우엉", status: "caution", desc: "식이섬유는 좋지만 칼륨이 있어 섭취량을 조절하세요." },
      { name: "연근", status: "caution", desc: "칼륨 함량이 있어 적당량만 섭취하세요." },
      { name: "마", status: "caution", desc: "칼륨 함량이 있어 적당량만 섭취하세요." },
      { name: "도라지", status: "caution", desc: "칼륨 함량이 있어 적당량만 섭취하세요." },
      { name: "생강", status: "good", desc: "향신료로 소량 사용 시 나트륨 부담이 없습니다." },
      { name: "갈비탕", status: "bad", desc: "국물에 나트륨과 인이 많아 신장에 부담을 줍니다." },
      { name: "삼계탕", status: "caution", desc: "단백질이 많아 국물은 적당히 섭취하세요." },
      { name: "감자탕", status: "bad", desc: "국물의 나트륨과 인이 매우 높습니다." },
      { name: "육개장", status: "bad", desc: "국물의 나트륨 함량이 높습니다." },
      { name: "설렁탕", status: "bad", desc: "국물의 나트륨과 인이 높습니다." },
      { name: "김치찌개", status: "bad", desc: "김치와 국물의 나트륨 함량이 매우 높습니다." },
      { name: "된장찌개", status: "bad", desc: "된장의 나트륨 함량이 높습니다." },
      { name: "순두부찌개", status: "caution", desc: "두부 단백질이 있어 국물은 적당히 섭취하세요." },
      { name: "부대찌개", status: "bad", desc: "가공육과 나트륨 함량이 매우 높습니다." },
      { name: "추어탕", status: "caution", desc: "단백질이 많아 국물은 적당히 섭취하세요." },
      { name: "떡볶이", status: "caution", desc: "떡의 탄수화물과 양념의 나트륨이 있습니다." },
      { name: "김밥", status: "caution", desc: "백미밥과 재료의 나트륨을 고려해 적당량만 섭취하세요." },
      { name: "순대", status: "bad", desc: "당면과 소금 간으로 나트륨·인이 높습니다." },
      { name: "어묵", status: "bad", desc: "나트륨과 인 첨가물이 많은 가공식품입니다." },
      { name: "만두", status: "caution", desc: "만두소의 나트륨을 고려해 적당량만 섭취하세요." },
      { name: "쫄면", status: "caution", desc: "면과 양념의 나트륨을 고려해 적당량만 섭취하세요." },
      { name: "치킨", status: "bad", desc: "튀김옷과 양념의 나트륨·인 함량이 높습니다." },
      { name: "피자", status: "bad", desc: "치즈와 가공육의 나트륨·인 함량이 높습니다." },
      { name: "족발", status: "caution", desc: "단백질이 많고 소스에 나트륨이 있어 적당량만 섭취하세요." },
      { name: "보쌈", status: "caution", desc: "단백질이 많아 적당량만 섭취하세요." },
      { name: "곱창", status: "caution", desc: "단백질과 인 함량이 있어 적당량만 섭취하세요." },
      { name: "인절미", status: "caution", desc: "찹쌀의 탄수화물이 있어 적당량만 섭취하세요." },
      { name: "송편", status: "caution", desc: "쌀가루의 탄수화물이 있어 적당량만 섭취하세요." },
      { name: "백설기", status: "good", desc: "첨가물이 적어 비교적 무난한 간식입니다." },
      { name: "가래떡", status: "caution", desc: "탄수화물이 있어 적당량만 섭취하세요." },
      { name: "찹쌀떡", status: "caution", desc: "찹쌀의 탄수화물이 있어 적당량만 섭취하세요." },
      { name: "닭고기", status: "caution", desc: "단백질과 인 함량이 있어 껍질을 제거하고 적당량만 섭취하세요." },
      { name: "오리고기", status: "caution", desc: "단백질과 인 함량이 있어 적당량만 섭취하세요." },
      { name: "양고기", status: "caution", desc: "단백질과 인 함량이 있어 적당량만 섭취하세요." },
      { name: "삼겹살", status: "caution", desc: "단백질과 인 함량이 있어 적당량만 섭취하세요." },
      { name: "고등어", status: "good", desc: "적당한 단백질원이며 소금간을 최소화하면 좋습니다." },
      { name: "갈치", status: "good", desc: "담백한 흰살 생선으로 무난합니다." },
      { name: "삼치", status: "good", desc: "담백한 생선으로 무난한 편입니다." },
      { name: "조기", status: "caution", desc: "자반 등 염장 제품은 나트륨이 높아 주의하세요." },
      { name: "명태", status: "good", desc: "저지방 담백한 생선입니다." },
      { name: "장어", status: "caution", desc: "단백질과 인 함량이 높아 적당량만 섭취하세요." },
      { name: "소금", status: "bad", desc: "나트륨을 직접 섭취하는 것으로 신장에 부담을 줍니다." },
      { name: "고추장", status: "bad", desc: "나트륨 함량이 높은 조미료입니다." },
      { name: "식초", status: "good", desc: "나트륨이 없는 조미료입니다." },
      { name: "후추", status: "good", desc: "나트륨이 없는 향신료입니다." },
      { name: "참기름", status: "good", desc: "나트륨이 없는 지방입니다." },
      { name: "들기름", status: "good", desc: "나트륨이 없는 지방입니다." },
      { name: "고춧가루", status: "good", desc: "소량 사용 시 나트륨 부담이 없는 향신료입니다." },
      { name: "밀가루", status: "caution", desc: "정제 곡물로 가공품에 따라 인 첨가물이 있을 수 있습니다." },
      { name: "부침가루", status: "caution", desc: "제품에 나트륨이 첨가된 경우가 많습니다." },
      { name: "튀김가루", status: "caution", desc: "제품에 나트륨이 첨가된 경우가 많습니다." },
      { name: "전분가루", status: "caution", desc: "정제 탄수화물로 섭취량 조절이 필요합니다." },
      { name: "빵가루", status: "caution", desc: "정제 탄수화물과 나트륨이 있는 제품이 많습니다." },
      { name: "코코아가루", status: "caution", desc: "무가당 기준 적당량은 무난하나 인 함량이 있습니다." },
      { name: "단백질보충제", status: "bad", desc: "과다 섭취 시 단백질·인 부담이 커져 신장에 좋지 않습니다." },
    ],
    stages: [
      {
        key: "general",
        label: "일반적인 신장 건강 관리",
        guidance: "신장 기능이 정상이거나 초기 위험군이라면 나트륨을 하루 2,000mg 이하로 줄이고 균형 잡힌 식사를 유지하는 것으로 충분합니다.",
        meals: [
          {
            title: "저염·저칼륨 식단 A",
            breakfast: ["백미밥", "달걀흰자찜", "양배추나물(데침)"],
            lunch: ["백미밥", "흰살생선구이", "무나물"],
            dinner: ["식빵 샌드위치(저염 재료)", "오이무침"],
            snack: ["사과(껍질 제거)"],
          },
          {
            title: "저염·저칼륨 식단 B",
            breakfast: ["백미죽", "콜리플라워볶음"],
            lunch: ["백미밥", "두부조림(저염)", "양파볶음"],
            dinner: ["백미밥", "대구탕(저염, 데친 채소)"],
            snack: ["파인애플 소량"],
          },
        ],
      },
      {
        key: "ckd_early",
        label: "만성 신부전 초기 (1-3단계)",
        guidance: "단백질을 체중 kg당 0.8g 내외로 조절하고, 칼륨·인이 높은 식품 섭취를 줄이는 것이 중요합니다. 정기적인 혈액검사로 상태를 확인하세요.",
        meals: [
          {
            title: "단백질 조절 식단 A",
            breakfast: ["백미죽", "달걀흰자 1개", "오이무침"],
            lunch: ["백미밥", "흰살생선 소량", "데친 양배추"],
            dinner: ["백미밥", "두부조림 소량", "무나물"],
            snack: ["사과 반쪽"],
          },
          {
            title: "단백질 조절 식단 B",
            breakfast: ["식빵 1장", "달걀흰자후라이"],
            lunch: ["백미밥", "닭가슴살 소량", "콜리플라워찜"],
            dinner: ["백미밥", "대구조림(저염)"],
            snack: ["파인애플 소량"],
          },
        ],
      },
      {
        key: "ckd_late",
        label: "만성 신부전 후기 (4-5단계, 투석 전)",
        guidance: "단백질을 더욱 엄격히 제한(0.6~0.8g/kg)하고 칼륨·인·나트륨·수분 섭취를 전문의 지시에 따라 세밀하게 관리해야 합니다. 반드시 신장내과 전문의 및 영양사의 처방을 따르세요.",
        meals: [
          {
            title: "저단백·저칼륨 식단 A",
            breakfast: ["흰죽", "저염 나물 소량"],
            lunch: ["백미밥", "저단백 흰살생선 소량", "데친 양배추"],
            dinner: ["당면잡채(저염)", "무나물"],
            snack: ["데친 사과 소량"],
          },
          {
            title: "저단백·저칼륨 식단 B",
            breakfast: ["흰죽", "계란흰자 1/2개"],
            lunch: ["백미밥", "두부 1/4모", "콜리플라워찜"],
            dinner: ["쌀국수(저염 육수)", "오이무침"],
            snack: ["파인애플 소량"],
          },
        ],
      },
    ],
  },

  diabetes: {
    label: "당뇨",
    icon: "droplet",
    intro: "혈당 관리에 좋은 음식인지 확인해보세요",
    note: "혈당 반응은 개인차가 있으니 식후 혈당을 함께 확인하세요.",
    foods: [
      { name: "현미밥", status: "good", desc: "혈당지수(GI)가 낮고 식이섬유가 풍부해 혈당 상승이 완만합니다." },
      { name: "브로콜리", status: "good", desc: "당질이 적고 식이섬유가 풍부한 저혈당 채소입니다." },
      { name: "시금치", status: "good", desc: "당질이 낮고 미네랄이 풍부한 채소입니다." },
      { name: "오이", status: "good", desc: "당질과 칼로리가 낮아 혈당에 미치는 영향이 적습니다." },
      { name: "닭가슴살", status: "good", desc: "탄수화물이 없는 고단백 식품으로 혈당 관리에 도움이 됩니다." },
      { name: "생선", status: "good", desc: "오메가3와 단백질이 풍부해 혈당 관리에 유리합니다." },
      { name: "두부", status: "good", desc: "저탄수화물 고단백 식품으로 혈당 부담이 적습니다." },
      { name: "견과류", status: "good", desc: "소량 섭취 시 혈당을 완만하게 유지하는 데 도움이 됩니다." },
      { name: "계란", status: "good", desc: "탄수화물이 거의 없어 혈당에 영향이 적은 단백질원입니다." },
      { name: "콩류", status: "good", desc: "식이섬유가 풍부해 혈당 상승을 완화시켜 줍니다." },
      { name: "무가당 요거트", status: "good", desc: "당분이 첨가되지 않아 혈당 부담이 적은 유제품입니다." },
      { name: "아보카도", status: "good", desc: "당질이 낮고 좋은 지방이 풍부해 혈당 관리에 도움을 줍니다." },
      { name: "블루베리", status: "good", desc: "GI가 낮은 편이며 항산화 성분이 풍부한 과일입니다." },
      { name: "올리브오일", status: "good", desc: "혈당에 영향을 주지 않는 건강한 지방입니다." },
      { name: "귀리", status: "good", desc: "수용성 식이섬유가 풍부해 혈당 상승을 완만하게 합니다." },
      { name: "딸기", status: "good", desc: "GI가 낮고 식이섬유가 풍부한 과일입니다." },
      { name: "키위", status: "good", desc: "GI가 낮은 편이며 비타민C가 풍부한 과일입니다." },
      { name: "버섯", status: "good", desc: "당질이 거의 없고 식이섬유가 풍부합니다." },
      { name: "콩나물", status: "good", desc: "당질이 낮고 식이섬유가 풍부한 채소입니다." },
      { name: "소고기", status: "good", desc: "탄수화물이 없는 단백질원으로 혈당 부담이 적습니다." },
      { name: "두유", status: "good", desc: "무가당 제품 기준 혈당 부담이 적은 식물성 음료입니다." },
      { name: "참치", status: "good", desc: "탄수화물이 거의 없는 단백질원입니다." },
      { name: "고구마", status: "caution", desc: "백미보다 GI는 낮지만 탄수화물량이 많아 섭취량 조절이 필요합니다." },
      { name: "감자", status: "caution", desc: "GI가 높은 편이라 섭취량을 제한하는 것이 좋습니다." },
      { name: "옥수수", status: "caution", desc: "당질이 많아 1회 섭취량을 조절해야 합니다." },
      { name: "바나나", status: "caution", desc: "당질이 많은 과일이라 적당량만 섭취하세요." },
      { name: "포도", status: "caution", desc: "당도가 높아 소량만 섭취하는 것이 좋습니다." },
      { name: "흰쌀밥", status: "caution", desc: "GI가 높은 편이라 현미·잡곡과 섞어 먹는 것이 좋습니다." },
      { name: "우유", status: "caution", desc: "유당이 포함되어 있어 섭취량 조절이 필요합니다." },
      { name: "복숭아", status: "caution", desc: "당분이 있어 적당량만 섭취하세요." },
      { name: "배", status: "caution", desc: "당분이 있어 적당량만 섭취하는 것이 좋습니다." },
      { name: "체리", status: "caution", desc: "당분이 있어 적당량만 섭취하세요." },
      { name: "수박", status: "caution", desc: "GI는 높지만 수분이 많아 소량은 괜찮으나 과다 섭취는 주의하세요." },
      { name: "김치", status: "caution", desc: "당질은 낮은 편이나 나트륨이 있어 적당량만 섭취하세요." },
      { name: "감", status: "bad", desc: "당도가 매우 높아 혈당을 빠르게 올릴 수 있습니다." },
      { name: "설탕", status: "bad", desc: "혈당을 급격히 상승시키는 대표적인 식품입니다." },
      { name: "탄산음료", status: "bad", desc: "당분이 매우 높아 혈당을 급격히 올립니다." },
      { name: "흰빵", status: "bad", desc: "정제 탄수화물로 혈당 상승이 빠릅니다." },
      { name: "과자", status: "bad", desc: "정제 탄수화물과 당분이 많아 혈당에 좋지 않습니다." },
      { name: "케이크", status: "bad", desc: "당분과 지방이 많아 혈당과 체중 모두에 부담을 줍니다." },
      { name: "꿀", status: "bad", desc: "천연이라도 당분 농도가 매우 높아 혈당을 급격히 올립니다." },
      { name: "튀김류", status: "bad", desc: "높은 열량과 정제 탄수화물 조합으로 혈당 관리에 좋지 않습니다." },
      { name: "라면", status: "bad", desc: "정제 탄수화물과 나트륨이 많아 혈당·혈압 모두에 부담을 줍니다." },
      { name: "떡", status: "bad", desc: "정제 탄수화물 함량이 높아 혈당을 빠르게 올립니다." },
      { name: "귤", status: "caution", desc: "당분이 있어 적당량만 섭취하세요." },
      { name: "망고", status: "caution", desc: "당도가 높은 편이라 적당량만 섭취하세요." },
      { name: "석류", status: "caution", desc: "당분이 있어 적당량만 섭취하세요." },
      { name: "자몽", status: "good", desc: "GI가 낮은 편의 과일입니다." },
      { name: "살구", status: "caution", desc: "당분이 있어 적당량만 섭취하세요." },
      { name: "우엉", status: "good", desc: "식이섬유가 풍부해 혈당 상승을 완만하게 합니다." },
      { name: "연근", status: "caution", desc: "탄수화물이 있어 섭취량을 조절하세요." },
      { name: "마", status: "good", desc: "식이섬유가 풍부해 혈당이 완만하게 오릅니다." },
      { name: "도라지", status: "good", desc: "당질이 낮은 뿌리채소입니다." },
      { name: "생강", status: "good", desc: "혈당에 미치는 영향이 적은 향신료입니다." },
      { name: "갈비탕", status: "caution", desc: "기름기가 있어 적당량만 섭취하세요." },
      { name: "삼계탕", status: "good", desc: "탄수화물이 적은 편의 보양식입니다." },
      { name: "감자탕", status: "caution", desc: "감자로 인한 탄수화물이 있습니다." },
      { name: "육개장", status: "caution", desc: "매운 양념에 당분이 있을 수 있습니다." },
      { name: "설렁탕", status: "good", desc: "탄수화물이 적은 편이나 국물은 주의하세요." },
      { name: "김치찌개", status: "caution", desc: "자극적인 양념은 적당량만 섭취하세요." },
      { name: "된장찌개", status: "good", desc: "당질이 낮은 편의 찌개입니다." },
      { name: "순두부찌개", status: "good", desc: "당질이 낮은 편의 찌개입니다." },
      { name: "부대찌개", status: "bad", desc: "가공육과 면사리로 탄수화물·나트륨이 높습니다." },
      { name: "추어탕", status: "good", desc: "당질이 낮은 편의 보양식입니다." },
      { name: "떡볶이", status: "bad", desc: "정제 탄수화물과 당분이 많아 혈당을 빠르게 올립니다." },
      { name: "김밥", status: "caution", desc: "흰쌀밥의 탄수화물을 고려해 적당량만 섭취하세요." },
      { name: "순대", status: "caution", desc: "당면의 탄수화물이 있어 적당량만 섭취하세요." },
      { name: "어묵", status: "caution", desc: "전분이 포함되어 있어 적당량만 섭취하세요." },
      { name: "만두", status: "caution", desc: "만두피의 탄수화물이 있어 적당량만 섭취하세요." },
      { name: "쫄면", status: "bad", desc: "정제 탄수화물과 매운 양념의 당분이 혈당을 올립니다." },
      { name: "치킨", status: "caution", desc: "튀김옷의 탄수화물을 고려해 적당량만 섭취하세요." },
      { name: "피자", status: "caution", desc: "도우의 탄수화물을 고려해 적당량만 섭취하세요." },
      { name: "족발", status: "good", desc: "탄수화물이 낮은 편의 음식입니다." },
      { name: "보쌈", status: "good", desc: "탄수화물이 낮은 편의 음식입니다." },
      { name: "곱창", status: "caution", desc: "기름기가 있어 적당량만 섭취하세요." },
      { name: "인절미", status: "bad", desc: "정제 탄수화물로 혈당지수(GI)가 높은 편입니다." },
      { name: "송편", status: "caution", desc: "소 재료에 당분이 있어 적당량만 섭취하세요." },
      { name: "백설기", status: "bad", desc: "정제 쌀가루로 혈당지수(GI)가 높은 편입니다." },
      { name: "가래떡", status: "bad", desc: "정제 쌀가루로 혈당지수(GI)가 높은 편입니다." },
      { name: "찹쌀떡", status: "bad", desc: "소에 당분이 있어 혈당을 빠르게 올릴 수 있습니다." },
      { name: "닭고기", status: "good", desc: "탄수화물이 없는 단백질원입니다." },
      { name: "오리고기", status: "good", desc: "탄수화물이 없는 단백질원입니다." },
      { name: "양고기", status: "good", desc: "탄수화물이 없는 단백질원입니다." },
      { name: "삼겹살", status: "good", desc: "탄수화물이 없는 부위입니다." },
      { name: "고등어", status: "good", desc: "오메가3가 풍부하고 탄수화물이 없습니다." },
      { name: "갈치", status: "good", desc: "탄수화물이 없는 단백질원입니다." },
      { name: "삼치", status: "good", desc: "탄수화물이 없는 단백질원입니다." },
      { name: "조기", status: "good", desc: "탄수화물이 없는 단백질원입니다." },
      { name: "명태", status: "good", desc: "탄수화물이 없는 단백질원입니다." },
      { name: "장어", status: "good", desc: "탄수화물이 없으나 양념장은 주의하세요." },
      { name: "소금", status: "caution", desc: "혈당엔 직접 영향이 적으나 과다 섭취는 피하세요." },
      { name: "고추장", status: "caution", desc: "당분이 첨가되어 있어 적당량만 사용하세요." },
      { name: "식초", status: "good", desc: "식후 혈당 상승 완화에 도움이 된다고 알려져 있습니다." },
      { name: "후추", status: "good", desc: "혈당에 영향을 주지 않습니다." },
      { name: "참기름", status: "good", desc: "혈당에 미치는 영향이 적습니다." },
      { name: "들기름", status: "good", desc: "오메가3가 풍부한 지방입니다." },
      { name: "고춧가루", status: "good", desc: "혈당에 미치는 영향이 적습니다." },
      { name: "밀가루", status: "bad", desc: "정제 탄수화물로 혈당지수(GI)가 높은 편입니다." },
      { name: "부침가루", status: "bad", desc: "정제 탄수화물 함량이 높습니다." },
      { name: "튀김가루", status: "bad", desc: "정제 탄수화물과 튀김 조리로 혈당에 좋지 않습니다." },
      { name: "전분가루", status: "bad", desc: "혈당지수(GI)가 매우 높은 편입니다." },
      { name: "빵가루", status: "bad", desc: "정제 탄수화물 함량이 높습니다." },
      { name: "코코아가루", status: "good", desc: "무가당 제품 기준 당질이 낮습니다." },
      { name: "단백질보충제", status: "caution", desc: "제품에 따라 당분이 첨가된 경우가 있어 확인이 필요합니다." },
    ],
    stages: [
      {
        key: "general",
        label: "일반적인 혈당 관리",
        guidance: "정제 탄수화물과 당분을 줄이고 식이섬유가 풍부한 식품 위주로 규칙적인 식사 시간을 지키는 것이 기본입니다.",
        meals: [
          {
            title: "저혈당지수(GI) 식단 A",
            breakfast: ["귀리죽", "삶은 계란", "블루베리"],
            lunch: ["현미밥", "닭가슴살구이", "브로콜리찜"],
            dinner: ["현미밥", "두부조림", "시금치나물"],
            snack: ["무가당 요거트"],
          },
          {
            title: "저혈당지수(GI) 식단 B",
            breakfast: ["채소오믈렛", "아보카도 슬라이스"],
            lunch: ["잡곡밥", "생선구이", "오이무침"],
            dinner: ["콩나물국", "닭가슴살샐러드"],
            snack: ["견과류 한 줌"],
          },
        ],
      },
      {
        key: "t2dm_oral",
        label: "제2형 당뇨 (경구약 치료 중)",
        guidance: "매 끼니 탄수화물량을 일정하게 유지하고, 약물 복용 시간에 맞춰 식사 시간을 규칙적으로 지키는 것이 혈당 변동을 줄이는 데 중요합니다.",
        meals: [
          {
            title: "일정 탄수화물 식단 A",
            breakfast: ["귀리죽 1/2공기", "삶은 계란", "오이"],
            lunch: ["현미밥 2/3공기", "닭가슴살구이", "브로콜리찜"],
            dinner: ["현미밥 2/3공기", "두부조림", "시금치나물"],
            snack: ["무가당 요거트"],
          },
          {
            title: "일정 탄수화물 식단 B",
            breakfast: ["채소오믈렛", "방울토마토"],
            lunch: ["잡곡밥 2/3공기", "생선구이", "오이무침"],
            dinner: ["콩나물국", "닭가슴살샐러드"],
            snack: ["아몬드 5알"],
          },
        ],
      },
      {
        key: "insulin",
        label: "인슐린 치료 중",
        guidance: "매 끼니 탄수화물 양을 정확히 계산하여 인슐린 용량과 맞추는 것이 중요합니다. 아래 식단은 예시이며 반드시 담당 의료진이 안내한 탄수화물 계산법에 따라 조정하세요.",
        meals: [
          {
            title: "탄수화물 계산 식단 A",
            breakfast: ["귀리죽(탄수화물 30g 상당)", "삶은 계란"],
            lunch: ["현미밥 1/2공기(탄수화물 45g 상당)", "닭가슴살구이", "브로콜리찜"],
            dinner: ["현미밥 1/2공기", "두부조림", "시금치나물"],
            snack: ["무가당 요거트(탄수화물 10g 상당)"],
          },
          {
            title: "탄수화물 계산 식단 B",
            breakfast: ["호밀빵 1장(탄수화물 15g 상당)", "달걀흰자후라이"],
            lunch: ["잡곡밥 1/2공기", "고등어구이", "브로콜리"],
            dinner: ["현미밥 1/2공기", "두부스테이크", "콩류샐러드"],
            snack: ["블루베리 한 줌(탄수화물 15g 상당)"],
          },
        ],
      },
    ],
  },

  hypertension: {
    label: "고혈압",
    icon: "activity",
    intro: "혈압 관리에 좋은 음식인지 확인해보세요",
    note: "나트륨 섭취를 줄이고 칼륨이 풍부한 식품을 곁들이는 것이 도움이 됩니다.",
    foods: [
      { name: "바나나", status: "good", desc: "칼륨이 풍부해 나트륨 배출과 혈압 조절에 도움이 됩니다." },
      { name: "시금치", status: "good", desc: "칼륨과 마그네슘이 풍부한 대표적인 혈압 관리 채소입니다." },
      { name: "브로콜리", status: "good", desc: "칼륨이 풍부하고 나트륨이 적어 혈압에 도움이 됩니다." },
      { name: "고구마", status: "good", desc: "칼륨 함량이 높아 혈압 관리에 도움을 주는 식품입니다." },
      { name: "저지방 우유", status: "good", desc: "칼슘과 칼륨이 풍부해 DASH 식단에서 권장되는 식품입니다." },
      { name: "요거트", status: "good", desc: "무가당 제품 기준으로 칼슘과 칼륨 보충에 도움이 됩니다." },
      { name: "오트밀", status: "good", desc: "식이섬유가 풍부하고 나트륨이 없는 곡물입니다." },
      { name: "연어", status: "good", desc: "오메가3가 풍부해 혈관 건강과 혈압 관리에 도움이 됩니다." },
      { name: "아보카도", status: "good", desc: "칼륨이 풍부하고 나트륨이 거의 없는 과일입니다." },
      { name: "마늘", status: "good", desc: "혈압을 낮추는 데 도움이 된다고 알려진 향신 채소입니다." },
      { name: "토마토", status: "good", desc: "칼륨이 풍부하고 나트륨이 적은 채소입니다." },
      { name: "콩류", status: "good", desc: "칼륨과 식이섬유가 풍부해 혈압 관리에 좋습니다." },
      { name: "무염 견과류", status: "good", desc: "소금 첨가가 없는 제품은 혈압 관리에 도움이 됩니다." },
      { name: "올리브오일", status: "good", desc: "나트륨이 없고 불포화지방이 풍부한 건강한 지방입니다." },
      { name: "사과", status: "good", desc: "칼륨이 풍부하고 나트륨이 거의 없는 과일입니다." },
      { name: "수박", status: "good", desc: "칼륨이 풍부해 나트륨 배출과 혈압 관리에 도움이 됩니다." },
      { name: "복숭아", status: "good", desc: "칼륨이 풍부한 과일입니다." },
      { name: "딸기", status: "good", desc: "칼륨과 항산화 성분이 풍부한 과일입니다." },
      { name: "배", status: "good", desc: "칼륨이 풍부하고 나트륨이 거의 없는 과일입니다." },
      { name: "감", status: "good", desc: "칼륨이 풍부한 과일입니다." },
      { name: "버섯", status: "good", desc: "칼륨이 풍부하고 나트륨이 없는 식품입니다." },
      { name: "치즈", status: "caution", desc: "칼슘은 풍부하지만 나트륨 함량이 높은 편이라 소량만 섭취하세요." },
      { name: "빵", status: "caution", desc: "일반 빵은 반죽 과정에서 나트륨이 첨가되어 섭취량 조절이 필요합니다." },
      { name: "통조림 과일", status: "caution", desc: "시럽에 나트륨·당분이 있을 수 있어 국물은 피하는 것이 좋습니다." },
      { name: "소스류", status: "caution", desc: "케첩, 마요네즈 등은 나트륨이 숨어있어 소량만 사용하세요." },
      { name: "소고기", status: "caution", desc: "조리·양념 방식에 따라 나트륨이 늘어날 수 있어 저염 조리법을 사용하세요." },
      { name: "참치", status: "caution", desc: "통조림 제품은 나트륨이 있어 저염 제품을 선택하세요." },
      { name: "라면", status: "bad", desc: "나트륨 함량이 매우 높아 혈압에 직접적으로 좋지 않습니다." },
      { name: "젓갈", status: "bad", desc: "염장식품으로 나트륨이 매우 높습니다." },
      { name: "장아찌", status: "bad", desc: "고염분 저장식품으로 혈압에 좋지 않습니다." },
      { name: "가공육", status: "bad", desc: "햄, 소시지, 베이컨 등은 나트륨 함량이 매우 높습니다." },
      { name: "짠 국물요리", status: "bad", desc: "국물까지 섭취하면 나트륨 섭취량이 크게 늘어납니다." },
      { name: "과자", status: "bad", desc: "가공 과정에서 나트륨과 트랜스지방이 많이 포함됩니다." },
      { name: "피클", status: "bad", desc: "절임 과정에서 나트륨이 매우 높아집니다." },
      { name: "양념치킨", status: "bad", desc: "튀김과 양념 모두 나트륨·지방 함량이 높습니다." },
      { name: "패스트푸드", status: "bad", desc: "나트륨과 포화지방이 매우 높은 편입니다." },
      { name: "간장", status: "bad", desc: "소량이라도 나트륨 농도가 매우 높은 조미료입니다." },
      { name: "김치", status: "bad", desc: "나트륨 함량이 높아 혈압에 부담을 줄 수 있습니다." },
      { name: "된장", status: "bad", desc: "나트륨 함량이 매우 높은 발효 조미료입니다." },
      { name: "귤", status: "good", desc: "칼륨이 풍부한 과일입니다." },
      { name: "망고", status: "good", desc: "칼륨이 풍부한 과일입니다." },
      { name: "석류", status: "good", desc: "칼륨과 항산화 성분이 풍부합니다." },
      { name: "자몽", status: "caution", desc: "일부 혈압약과 상호작용할 수 있어 복용 중이면 의료진과 상담하세요." },
      { name: "살구", status: "good", desc: "칼륨이 풍부한 과일입니다." },
      { name: "우엉", status: "good", desc: "칼륨이 풍부한 뿌리채소입니다." },
      { name: "연근", status: "good", desc: "칼륨이 풍부한 뿌리채소입니다." },
      { name: "마", status: "good", desc: "칼륨이 풍부한 뿌리채소입니다." },
      { name: "도라지", status: "good", desc: "칼륨이 풍부한 뿌리채소입니다." },
      { name: "생강", status: "good", desc: "나트륨 없이 풍미를 더할 수 있습니다." },
      { name: "갈비탕", status: "bad", desc: "국물의 나트륨 함량이 매우 높습니다." },
      { name: "삼계탕", status: "caution", desc: "국물에 나트륨이 있어 적당량만 섭취하세요." },
      { name: "감자탕", status: "bad", desc: "나트륨 함량이 매우 높습니다." },
      { name: "육개장", status: "bad", desc: "나트륨 함량이 높습니다." },
      { name: "설렁탕", status: "bad", desc: "국물의 나트륨 함량이 높습니다." },
      { name: "김치찌개", status: "bad", desc: "나트륨 함량이 매우 높습니다." },
      { name: "된장찌개", status: "bad", desc: "나트륨 함량이 높습니다." },
      { name: "순두부찌개", status: "caution", desc: "국물에 나트륨이 있어 적당량만 섭취하세요." },
      { name: "부대찌개", status: "bad", desc: "나트륨 함량이 매우 높습니다." },
      { name: "추어탕", status: "caution", desc: "국물에 나트륨이 있어 적당량만 섭취하세요." },
      { name: "떡볶이", status: "caution", desc: "매운 양념에 나트륨이 있어 적당량만 섭취하세요." },
      { name: "김밥", status: "caution", desc: "단무지·햄 등 재료에 나트륨이 있습니다." },
      { name: "순대", status: "bad", desc: "나트륨 함량이 높은 편입니다." },
      { name: "어묵", status: "bad", desc: "나트륨 함량이 매우 높습니다." },
      { name: "만두", status: "caution", desc: "만두소에 나트륨이 있어 적당량만 섭취하세요." },
      { name: "쫄면", status: "caution", desc: "양념에 나트륨이 있어 적당량만 섭취하세요." },
      { name: "치킨", status: "bad", desc: "나트륨과 포화지방 함량이 높습니다." },
      { name: "피자", status: "bad", desc: "치즈와 가공육의 나트륨 함량이 높습니다." },
      { name: "족발", status: "bad", desc: "소스와 삶는 국물에 나트륨이 있습니다." },
      { name: "보쌈", status: "caution", desc: "김치와 소스에 나트륨이 있습니다." },
      { name: "곱창", status: "caution", desc: "양념에 나트륨이 있어 적당량만 섭취하세요." },
      { name: "인절미", status: "good", desc: "나트륨이 거의 없는 간식입니다." },
      { name: "송편", status: "good", desc: "나트륨 함량이 적은 편입니다." },
      { name: "백설기", status: "good", desc: "나트륨이 거의 없는 간식입니다." },
      { name: "가래떡", status: "good", desc: "나트륨이 없는 간식입니다." },
      { name: "찹쌀떡", status: "good", desc: "나트륨 함량이 적은 편입니다." },
      { name: "닭고기", status: "good", desc: "껍질을 제거하면 나트륨 부담이 적습니다." },
      { name: "오리고기", status: "caution", desc: "지방이 많은 부위는 적당량만 섭취하세요." },
      { name: "양고기", status: "caution", desc: "포화지방이 있어 적당량만 섭취하세요." },
      { name: "삼겹살", status: "caution", desc: "포화지방이 많아 적당량만 섭취하세요." },
      { name: "고등어", status: "good", desc: "오메가3가 풍부해 혈관 건강에 도움이 됩니다." },
      { name: "갈치", status: "good", desc: "저염 조리 시 무난한 생선입니다." },
      { name: "삼치", status: "good", desc: "오메가3가 풍부한 생선입니다." },
      { name: "조기", status: "caution", desc: "염장 제품은 나트륨이 높아 주의하세요." },
      { name: "명태", status: "good", desc: "저염 조리 시 무난한 생선입니다." },
      { name: "장어", status: "caution", desc: "양념장에 나트륨이 있어 적당량만 섭취하세요." },
      { name: "소금", status: "bad", desc: "혈압을 직접 상승시키는 주요 원인입니다." },
      { name: "고추장", status: "bad", desc: "나트륨 함량이 높은 조미료입니다." },
      { name: "식초", status: "good", desc: "나트륨 없이 풍미를 더할 수 있습니다." },
      { name: "후추", status: "good", desc: "나트륨 없이 풍미를 더할 수 있습니다." },
      { name: "참기름", status: "good", desc: "나트륨이 없는 조미료입니다." },
      { name: "들기름", status: "good", desc: "불포화지방이 풍부합니다." },
      { name: "고춧가루", status: "good", desc: "나트륨 없이 풍미를 더할 수 있습니다." },
      { name: "밀가루", status: "good", desc: "밀가루 자체의 나트륨은 낮은 편입니다." },
      { name: "부침가루", status: "caution", desc: "제품에 나트륨이 첨가된 경우가 많습니다." },
      { name: "튀김가루", status: "caution", desc: "제품에 나트륨이 첨가된 경우가 많습니다." },
      { name: "전분가루", status: "good", desc: "나트륨이 없는 재료입니다." },
      { name: "빵가루", status: "caution", desc: "제품에 나트륨이 첨가된 경우가 많습니다." },
      { name: "코코아가루", status: "good", desc: "나트륨이 없는 재료입니다." },
      { name: "단백질보충제", status: "caution", desc: "나트륨이 첨가된 제품이 있어 확인이 필요합니다." },
    ],
    stages: [
      {
        key: "general",
        label: "일반적인 혈압 관리",
        guidance: "나트륨 섭취를 하루 2,000mg 이하로 줄이고 칼륨이 풍부한 채소·과일을 곁들이는 DASH 식단 원칙을 따르는 것이 좋습니다.",
        meals: [
          {
            title: "저염 DASH 식단 A",
            breakfast: ["오트밀", "저지방 우유", "바나나"],
            lunch: ["현미밥", "연어구이(저염)", "시금치나물"],
            dinner: ["잡곡밥", "두부조림(저염)", "브로콜리찜"],
            snack: ["무염 견과류"],
          },
          {
            title: "저염 DASH 식단 B",
            breakfast: ["통밀토스트", "아보카도", "토마토"],
            lunch: ["잡곡밥", "닭가슴살구이(저염)", "콩나물무침(저염)"],
            dinner: ["현미밥", "고구마", "채소샐러드(드레싱 소량)"],
            snack: ["사과"],
          },
        ],
      },
      {
        key: "stage1",
        label: "고혈압 1단계 (생활습관 개선)",
        guidance: "약물치료 전 단계라면 나트륨을 하루 1,500~2,000mg 수준으로 줄이고 체중 관리, 운동을 병행하는 것이 혈압 조절에 큰 도움이 됩니다.",
        meals: [
          {
            title: "생활습관 개선 식단 A",
            breakfast: ["오트밀", "저지방 우유", "바나나"],
            lunch: ["현미밥", "연어구이(저염)", "시금치나물"],
            dinner: ["잡곡밥", "두부조림(저염)", "브로콜리찜"],
            snack: ["무염 견과류"],
          },
          {
            title: "생활습관 개선 식단 B",
            breakfast: ["통밀토스트", "아보카도", "토마토"],
            lunch: ["잡곡밥", "닭가슴살구이(저염)", "콩나물무침(저염)"],
            dinner: ["현미밥", "고구마", "채소샐러드"],
            snack: ["사과"],
          },
        ],
      },
      {
        key: "stage2",
        label: "고혈압 2단계 (약물치료 중)",
        guidance: "약물치료 중이라면 나트륨을 하루 1,500mg 이하로 더욱 엄격히 제한하고, 가공식품·국물요리를 최대한 피해야 합니다. 혈압약과 상호작용할 수 있는 자몽 등은 의료진과 상담하세요.",
        meals: [
          {
            title: "저염 강화 식단 A",
            breakfast: ["무가당 그릭요거트", "블루베리", "무염 견과류"],
            lunch: ["현미밥", "저염 두부스테이크", "브로콜리찜"],
            dinner: ["잡곡밥", "저염 생선조림", "시금치나물"],
            snack: ["바나나"],
          },
          {
            title: "저염 강화 식단 B",
            breakfast: ["오트밀", "사과"],
            lunch: ["현미밥", "저염 닭가슴살구이", "오이무침"],
            dinner: ["잡곡밥", "저염 콩류스튜", "양배추찜"],
            snack: ["무염 견과류 소량"],
          },
        ],
      },
    ],
  },

  liver: {
    label: "간기능",
    icon: "shield",
    intro: "간 건강에 좋은 음식인지 확인해보세요",
    note: "음주와 고지방·자극적인 음식을 줄이는 것이 간 건강의 기본입니다.",
    foods: [
      { name: "두부", status: "good", desc: "저지방 고단백 식품으로 간에 부담이 적은 단백질원입니다." },
      { name: "브로콜리", status: "good", desc: "항산화 성분이 풍부해 간 해독 작용에 도움을 줍니다." },
      { name: "마늘", status: "good", desc: "간 효소 활성화에 도움이 된다고 알려진 식품입니다." },
      { name: "시금치", status: "good", desc: "항산화 비타민이 풍부해 간세포 보호에 도움이 됩니다." },
      { name: "당근", status: "good", desc: "베타카로틴이 풍부해 간 건강에 도움을 줍니다." },
      { name: "사과", status: "good", desc: "식이섬유와 항산화 성분이 간 건강에 도움을 줍니다." },
      { name: "귀리", status: "good", desc: "식이섬유가 풍부해 지방간 예방에 도움이 됩니다." },
      { name: "현미밥", status: "good", desc: "정제되지 않은 곡물로 간에 부담이 적은 탄수화물원입니다." },
      { name: "흰살생선", status: "good", desc: "저지방 고단백 식품으로 간에 부담이 적습니다." },
      { name: "달걀흰자", status: "good", desc: "지방이 적은 양질의 단백질원입니다." },
      { name: "녹차", status: "good", desc: "카테킨 성분이 간 건강에 도움을 준다고 알려져 있습니다." },
      { name: "올리브오일", status: "good", desc: "불포화지방으로 간에 부담이 적은 지방입니다." },
      { name: "블루베리", status: "good", desc: "항산화 성분이 풍부해 간세포 손상 예방에 도움이 됩니다." },
      { name: "양배추", status: "good", desc: "해독 작용에 관여하는 성분이 풍부한 채소입니다." },
      { name: "미나리", status: "good", desc: "예로부터 간 해독에 좋다고 알려진 채소입니다." },
      { name: "수박", status: "good", desc: "수분과 항산화 성분이 풍부한 과일입니다." },
      { name: "복숭아", status: "good", desc: "식이섬유와 비타민이 풍부한 과일입니다." },
      { name: "딸기", status: "good", desc: "항산화 성분이 풍부해 간 건강에 도움이 됩니다." },
      { name: "배", status: "good", desc: "식이섬유가 풍부한 과일입니다." },
      { name: "버섯", status: "good", desc: "항산화 성분과 식이섬유가 풍부합니다." },
      { name: "붉은고기", status: "caution", desc: "지방 함량이 높은 부위는 간에 부담을 줄 수 있어 소량만 섭취하세요." },
      { name: "치즈", status: "caution", desc: "포화지방이 많아 과다 섭취 시 간에 부담이 될 수 있습니다." },
      { name: "전지 우유", status: "caution", desc: "지방 함량이 높아 저지방 제품이 더 적합합니다." },
      { name: "새우", status: "caution", desc: "콜레스테롤이 있어 적당량만 섭취하는 것이 좋습니다." },
      { name: "오징어", status: "caution", desc: "콜레스테롤이 있어 적당량만 섭취하세요." },
      { name: "커피", status: "caution", desc: "적당량은 간에 도움이 되나 과다 섭취는 피해야 합니다." },
      { name: "계란노른자", status: "caution", desc: "지방과 콜레스테롤이 있어 하루 섭취량 조절이 필요합니다." },
      { name: "소고기", status: "caution", desc: "지방이 많은 부위는 간에 부담을 줄 수 있어 살코기 위주로 소량만 섭취하세요." },
      { name: "돼지고기", status: "caution", desc: "지방 함량이 높은 부위는 간에 부담이 될 수 있습니다." },
      { name: "김치", status: "caution", desc: "나트륨이 있어 적당량만 섭취하세요." },
      { name: "술", status: "bad", desc: "간세포 손상을 직접적으로 유발하는 대표적인 원인입니다." },
      { name: "튀김류", status: "bad", desc: "높은 지방 함량이 지방간의 원인이 될 수 있습니다." },
      { name: "가공육", status: "bad", desc: "첨가물과 나트륨, 지방이 많아 간에 부담을 줍니다." },
      { name: "인스턴트식품", status: "bad", desc: "나트륨과 첨가물이 많아 간에 부담을 줄 수 있습니다." },
      { name: "버터", status: "bad", desc: "포화지방 함량이 매우 높아 과다 섭취를 피해야 합니다." },
      { name: "과자", status: "bad", desc: "트랜스지방과 정제 탄수화물이 많아 지방간 위험을 높입니다." },
      { name: "탄산음료", status: "bad", desc: "과당 함량이 높아 지방간 위험을 높일 수 있습니다." },
      { name: "내장류", status: "bad", desc: "간(liver) 등 내장류의 과다 섭취는 오히려 부담을 줄 수 있습니다." },
      { name: "귤", status: "good", desc: "비타민C와 항산화 성분이 풍부합니다." },
      { name: "망고", status: "good", desc: "항산화 성분이 풍부합니다." },
      { name: "석류", status: "good", desc: "폴리페놀 등 항산화 성분이 풍부합니다." },
      { name: "자몽", status: "caution", desc: "일부 약물 대사에 영향을 줄 수 있어 복용약이 있으면 주의하세요." },
      { name: "살구", status: "good", desc: "비타민A가 풍부합니다." },
      { name: "우엉", status: "good", desc: "식이섬유와 항산화 성분이 풍부합니다." },
      { name: "연근", status: "good", desc: "식이섬유가 풍부합니다." },
      { name: "마", status: "good", desc: "소화 흡수에 도움을 주는 식품입니다." },
      { name: "도라지", status: "good", desc: "사포닌 성분이 풍부합니다." },
      { name: "생강", status: "good", desc: "항염 성분이 있다고 알려져 있습니다." },
      { name: "갈비탕", status: "caution", desc: "기름기가 있어 적당량만 섭취하세요." },
      { name: "삼계탕", status: "good", desc: "살코기 위주로 섭취하면 부담이 적습니다." },
      { name: "감자탕", status: "caution", desc: "기름기가 많아 적당량만 섭취하세요." },
      { name: "육개장", status: "caution", desc: "자극적인 양념은 적당량만 섭취하세요." },
      { name: "설렁탕", status: "caution", desc: "기름기가 있어 적당량만 섭취하세요." },
      { name: "김치찌개", status: "caution", desc: "자극적인 음식은 적당량만 섭취하세요." },
      { name: "된장찌개", status: "caution", desc: "나트륨이 있어 국물은 적당히 섭취하세요." },
      { name: "순두부찌개", status: "good", desc: "저지방 단백질원인 두부가 주재료입니다." },
      { name: "부대찌개", status: "bad", desc: "가공육과 기름 함량이 높아 부담을 줍니다." },
      { name: "추어탕", status: "good", desc: "저지방 고단백 식품입니다." },
      { name: "떡볶이", status: "caution", desc: "자극적인 양념은 적당량만 섭취하세요." },
      { name: "김밥", status: "good", desc: "채소 위주 재료로 구성하면 무난한 편입니다." },
      { name: "순대", status: "caution", desc: "내장 부위가 포함되어 적당량만 섭취하세요." },
      { name: "어묵", status: "caution", desc: "가공식품으로 적당량만 섭취하세요." },
      { name: "만두", status: "caution", desc: "튀김만두는 기름 부담이 있어 찐만두를 추천합니다." },
      { name: "쫄면", status: "caution", desc: "자극적인 양념은 적당량만 섭취하세요." },
      { name: "치킨", status: "bad", desc: "튀김 기름이 간에 부담을 줄 수 있습니다." },
      { name: "피자", status: "caution", desc: "치즈의 포화지방은 적당량만 섭취하세요." },
      { name: "족발", status: "caution", desc: "지방이 많은 부위가 포함되어 적당량만 섭취하세요." },
      { name: "보쌈", status: "caution", desc: "돼지고기의 지방 함량을 고려해 살코기 위주로 섭취하세요." },
      { name: "곱창", status: "bad", desc: "내장 부위와 기름 함량이 많아 간에 부담을 줍니다." },
      { name: "인절미", status: "good", desc: "단순한 곡물 간식으로 무난한 편입니다." },
      { name: "송편", status: "good", desc: "찜으로 조리해 무난한 간식입니다." },
      { name: "백설기", status: "good", desc: "첨가물이 적어 무난한 편입니다." },
      { name: "가래떡", status: "good", desc: "단순한 곡물 간식입니다." },
      { name: "찹쌀떡", status: "good", desc: "무난한 간식이나 과다 섭취는 피하세요." },
      { name: "닭고기", status: "good", desc: "저지방 부위 위주로 섭취하면 무난합니다." },
      { name: "오리고기", status: "caution", desc: "지방 함량이 있어 적당량만 섭취하세요." },
      { name: "양고기", status: "caution", desc: "지방 함량이 있어 적당량만 섭취하세요." },
      { name: "삼겹살", status: "bad", desc: "고지방 부위로 간에 부담을 줄 수 있습니다." },
      { name: "고등어", status: "good", desc: "불포화지방이 풍부한 생선입니다." },
      { name: "갈치", status: "good", desc: "저지방 고단백 생선입니다." },
      { name: "삼치", status: "good", desc: "불포화지방이 풍부합니다." },
      { name: "조기", status: "good", desc: "비염장 기준 저지방 단백질원입니다." },
      { name: "명태", status: "good", desc: "저지방 고단백 생선입니다." },
      { name: "장어", status: "good", desc: "불포화지방과 비타민A가 풍부합니다." },
      { name: "소금", status: "caution", desc: "과다 섭취 시 부담이 될 수 있습니다." },
      { name: "고추장", status: "caution", desc: "자극적인 조미료로 적당량만 사용하세요." },
      { name: "식초", status: "good", desc: "소량 사용 시 무난한 조미료입니다." },
      { name: "후추", status: "good", desc: "소량 사용 시 무난한 향신료입니다." },
      { name: "참기름", status: "good", desc: "불포화지방이 풍부합니다." },
      { name: "들기름", status: "good", desc: "오메가3가 풍부해 항염에 도움이 됩니다." },
      { name: "고춧가루", status: "caution", desc: "과다 섭취 시 자극적일 수 있습니다." },
      { name: "밀가루", status: "caution", desc: "정제 탄수화물 과다 섭취는 지방간 위험을 높일 수 있습니다." },
      { name: "부침가루", status: "caution", desc: "부침 조리 시 기름 섭취가 늘어날 수 있습니다." },
      { name: "튀김가루", status: "bad", desc: "튀김 기름이 간에 부담을 줄 수 있습니다." },
      { name: "전분가루", status: "good", desc: "소량 사용 시 무난한 재료입니다." },
      { name: "빵가루", status: "caution", desc: "튀김옷으로 쓰이면 기름 섭취가 늘어납니다." },
      { name: "코코아가루", status: "good", desc: "폴리페놀 등 항산화 성분이 풍부합니다(무가당 기준)." },
      { name: "단백질보충제", status: "caution", desc: "과다 섭취 시 대사 부담이 될 수 있습니다." },
    ],
    stages: [
      {
        key: "general",
        label: "일반적인 간 건강 관리",
        guidance: "음주를 피하고 튀김·가공식품 섭취를 줄이며 항산화 성분이 풍부한 채소·과일을 충분히 섭취하는 것이 기본입니다.",
        meals: [
          {
            title: "간 건강 식단 A",
            breakfast: ["귀리죽", "달걀흰자찜", "당근라페"],
            lunch: ["현미밥", "흰살생선구이", "브로콜리찜"],
            dinner: ["현미밥", "두부조림", "시금치나물"],
            snack: ["블루베리"],
          },
          {
            title: "간 건강 식단 B",
            breakfast: ["사과", "그릭요거트(저지방)"],
            lunch: ["잡곡밥", "닭가슴살구이", "미나리무침"],
            dinner: ["현미밥", "채소된장국(저염)", "양배추찜"],
            snack: ["녹차"],
          },
        ],
      },
      {
        key: "elevated_enzymes",
        label: "간기능 수치 상승 (AST/ALT 상승)",
        guidance: "간 효소 수치가 상승했다면 음주를 완전히 중단하고 튀김·기름진 음식·과당·가공식품을 피해야 합니다. 간에 부담을 주는 약물이나 건강기능식품 복용도 의료진과 상담 후 결정하고, 원인 확인을 위한 정밀 검사를 받으세요.",
        meals: [
          {
            title: "간 효소 관리 식단 A",
            breakfast: ["귀리죽", "삶은 달걀흰자", "블루베리"],
            lunch: ["현미밥 소량", "흰살생선구이", "브로콜리찜"],
            dinner: ["두부조림", "미나리무침", "당근볶음"],
            snack: ["녹차"],
          },
          {
            title: "간 효소 관리 식단 B",
            breakfast: ["무가당 그릭요거트", "사과"],
            lunch: ["잡곡밥 소량", "닭가슴살구이", "양배추찜"],
            dinner: ["현미밥 소량", "흰살생선조림", "시금치나물"],
            snack: ["방울토마토"],
          },
        ],
      },
      {
        key: "fatty_liver",
        label: "지방간",
        guidance: "체중 감량과 함께 정제 탄수화물·과당·포화지방 섭취를 줄이는 것이 지방간 개선에 가장 중요합니다.",
        meals: [
          {
            title: "지방간 개선 식단 A",
            breakfast: ["삶은 달걀", "오이", "방울토마토"],
            lunch: ["현미밥 소량", "닭가슴살구이", "브로콜리찜"],
            dinner: ["두부조림", "시금치나물", "양배추찜"],
            snack: ["블루베리"],
          },
          {
            title: "지방간 개선 식단 B",
            breakfast: ["무가당 그릭요거트", "사과"],
            lunch: ["잡곡밥 소량", "흰살생선구이", "미나리무침"],
            dinner: ["현미밥 소량", "콩류샐러드", "당근볶음"],
            snack: ["녹차"],
          },
        ],
      },
      {
        key: "cirrhosis",
        label: "간경변 (저염·고단백 관리)",
        guidance: "복수·부종 예방을 위해 나트륨을 엄격히 제한하되, 근육 손실 방지를 위한 충분한 단백질 섭취가 필요합니다. 반드시 간전문의·영양사의 처방에 따라 조정하세요.",
        meals: [
          {
            title: "저염·고단백 식단 A",
            breakfast: ["흰죽(저염)", "달걀흰자찜"],
            lunch: ["백미밥", "저염 두부스테이크", "데친 브로콜리"],
            dinner: ["백미밥", "저염 흰살생선조림", "시금치나물"],
            snack: ["사과"],
          },
          {
            title: "저염·고단백 식단 B",
            breakfast: ["오트밀(저염)", "달걀흰자 1개"],
            lunch: ["백미밥", "저염 닭가슴살구이", "당근볶음"],
            dinner: ["백미밥", "저염 두부조림", "양배추찜"],
            snack: ["블루베리"],
          },
        ],
      },
    ],
  },

  diet: {
    label: "다이어트",
    icon: "flame",
    intro: "다이어트에 좋은 음식인지 확인해보세요",
    note: "총 섭취 칼로리와 활동량을 함께 고려하는 것이 중요합니다.",
    foods: [
      { name: "닭가슴살", status: "good", desc: "저지방 고단백 식품으로 포만감을 유지하며 체중 관리에 도움을 줍니다." },
      { name: "두부", status: "good", desc: "저칼로리 고단백 식물성 식품입니다." },
      { name: "계란", status: "good", desc: "포만감이 높은 양질의 단백질원입니다." },
      { name: "브로콜리", status: "good", desc: "저칼로리 고식이섬유 채소로 포만감 유지에 좋습니다." },
      { name: "오이", status: "good", desc: "칼로리가 매우 낮고 수분이 많아 다이어트 간식으로 좋습니다." },
      { name: "현미밥", status: "good", desc: "식이섬유가 풍부해 포만감이 오래 지속됩니다." },
      { name: "그릭요거트", status: "good", desc: "고단백 저당 제품 기준으로 다이어트에 도움이 됩니다." },
      { name: "연어", status: "good", desc: "양질의 단백질과 불포화지방으로 다이어트 식단에 적합합니다." },
      { name: "시금치", status: "good", desc: "저칼로리 고영양 채소입니다." },
      { name: "귀리", status: "good", desc: "식이섬유가 풍부해 포만감을 오래 유지시켜 줍니다." },
      { name: "사과", status: "good", desc: "식이섬유가 풍부한 저칼로리 과일입니다." },
      { name: "토마토", status: "good", desc: "칼로리가 낮고 포만감을 주는 채소입니다." },
      { name: "수박", status: "good", desc: "칼로리가 낮고 수분이 많은 과일입니다." },
      { name: "복숭아", status: "good", desc: "칼로리가 낮은 편의 과일입니다." },
      { name: "딸기", status: "good", desc: "저칼로리 고식이섬유 과일입니다." },
      { name: "버섯", status: "good", desc: "칼로리가 매우 낮고 포만감을 주는 식품입니다." },
      { name: "오징어", status: "good", desc: "저지방 고단백 식품입니다." },
      { name: "두유", status: "good", desc: "무가당 제품 기준 저칼로리 식물성 음료입니다." },
      { name: "김치", status: "good", desc: "저칼로리 발효식품입니다(나트륨 함량은 주의하세요)." },
      { name: "고구마", status: "caution", desc: "영양가는 좋지만 탄수화물량이 있어 섭취량 조절이 필요합니다." },
      { name: "견과류", status: "caution", desc: "건강한 지방이지만 칼로리가 높아 소량만 섭취하세요." },
      { name: "바나나", status: "caution", desc: "당분이 있어 적당량만 섭취하는 것이 좋습니다." },
      { name: "아보카도", status: "caution", desc: "건강한 지방이 풍부하지만 칼로리가 높아 섭취량 조절이 필요합니다." },
      { name: "감자", status: "caution", desc: "조리법에 따라 칼로리 차이가 크므로 튀기지 않고 섭취하세요." },
      { name: "흰쌀밥", status: "caution", desc: "정제 탄수화물로 과다 섭취 시 체중 관리에 불리합니다." },
      { name: "빵", status: "caution", desc: "정제 탄수화물과 당분이 많은 제품은 섭취량 조절이 필요합니다." },
      { name: "과일주스", status: "caution", desc: "생과일보다 당분이 농축되어 있어 섭취량에 주의하세요." },
      { name: "배", status: "caution", desc: "당분이 있어 적당량만 섭취하세요." },
      { name: "감", status: "caution", desc: "당분이 높은 편이라 적당량만 섭취하세요." },
      { name: "소고기", status: "caution", desc: "살코기는 좋지만 지방이 많은 부위는 칼로리가 높으니 부위를 선택하세요." },
      { name: "튀김류", status: "bad", desc: "칼로리와 지방 함량이 매우 높아 체중 관리에 좋지 않습니다." },
      { name: "과자", status: "bad", desc: "고칼로리 저영양 식품으로 다이어트에 방해가 됩니다." },
      { name: "케이크", status: "bad", desc: "당분과 지방이 매우 높은 고칼로리 식품입니다." },
      { name: "탄산음료", status: "bad", desc: "당분이 높고 영양가가 없어 체중 관리에 좋지 않습니다." },
      { name: "아이스크림", status: "bad", desc: "당분과 지방 함량이 높은 고칼로리 간식입니다." },
      { name: "술", status: "bad", desc: "칼로리가 높고 식욕을 자극해 체중 관리에 방해가 됩니다." },
      { name: "패스트푸드", status: "bad", desc: "고칼로리·고지방·고나트륨 조합으로 다이어트에 좋지 않습니다." },
      { name: "라면", status: "bad", desc: "정제 탄수화물과 나트륨, 지방이 높은 고칼로리 식품입니다." },
      { name: "초콜릿", status: "bad", desc: "당분과 지방이 많아 과다 섭취 시 체중 관리에 불리합니다." },
      { name: "귤", status: "good", desc: "칼로리가 낮은 편의 과일입니다." },
      { name: "망고", status: "caution", desc: "당분이 높은 편이라 적당량만 섭취하세요." },
      { name: "석류", status: "good", desc: "항산화 성분이 풍부한 저칼로리 과일입니다." },
      { name: "자몽", status: "good", desc: "칼로리가 낮은 편의 과일입니다." },
      { name: "살구", status: "good", desc: "칼로리가 낮은 편의 과일입니다." },
      { name: "우엉", status: "good", desc: "저칼로리 고식이섬유 채소입니다." },
      { name: "연근", status: "good", desc: "식이섬유가 풍부해 포만감을 줍니다." },
      { name: "마", status: "good", desc: "포만감을 주는 저칼로리 식품입니다." },
      { name: "도라지", status: "good", desc: "저칼로리 뿌리채소입니다." },
      { name: "생강", status: "good", desc: "저칼로리 향신 채소입니다." },
      { name: "갈비탕", status: "caution", desc: "고기와 기름으로 칼로리가 높은 편입니다." },
      { name: "삼계탕", status: "caution", desc: "한 마리 기준 칼로리가 높은 편입니다." },
      { name: "감자탕", status: "bad", desc: "칼로리와 나트륨이 모두 높은 편입니다." },
      { name: "육개장", status: "caution", desc: "고기와 기름으로 칼로리가 있는 편입니다." },
      { name: "설렁탕", status: "caution", desc: "곰탕류는 칼로리가 있는 편입니다." },
      { name: "김치찌개", status: "caution", desc: "돼지고기와 기름이 들어가 칼로리가 있습니다." },
      { name: "된장찌개", status: "good", desc: "저칼로리 찌개이나 나트륨은 주의하세요." },
      { name: "순두부찌개", status: "good", desc: "저칼로리 고단백 찌개입니다." },
      { name: "부대찌개", status: "bad", desc: "고칼로리·고나트륨 음식입니다." },
      { name: "추어탕", status: "good", desc: "고단백 저칼로리 보양식입니다." },
      { name: "떡볶이", status: "bad", desc: "탄수화물과 칼로리가 높은 편입니다." },
      { name: "김밥", status: "caution", desc: "탄수화물이 있어 적당량만 섭취하세요." },
      { name: "순대", status: "caution", desc: "칼로리가 있는 편입니다." },
      { name: "어묵", status: "caution", desc: "나트륨과 전분이 있어 적당량만 섭취하세요." },
      { name: "만두", status: "caution", desc: "칼로리가 있는 편이니 찐만두를 추천합니다." },
      { name: "쫄면", status: "caution", desc: "탄수화물이 많아 적당량만 섭취하세요." },
      { name: "치킨", status: "bad", desc: "고칼로리·고지방 음식입니다." },
      { name: "피자", status: "bad", desc: "칼로리가 매우 높은 편입니다." },
      { name: "족발", status: "caution", desc: "지방 함량이 있어 적당량만 섭취하세요." },
      { name: "보쌈", status: "caution", desc: "살코기 위주로 섭취하면 비교적 무난합니다." },
      { name: "곱창", status: "bad", desc: "고지방·고칼로리 음식입니다." },
      { name: "인절미", status: "caution", desc: "칼로리가 있는 편이라 적당량만 섭취하세요." },
      { name: "송편", status: "caution", desc: "칼로리가 있는 편이라 적당량만 섭취하세요." },
      { name: "백설기", status: "caution", desc: "탄수화물이 많아 적당량만 섭취하세요." },
      { name: "가래떡", status: "caution", desc: "칼로리가 있는 편이라 적당량만 섭취하세요." },
      { name: "찹쌀떡", status: "bad", desc: "당분과 칼로리가 높은 편입니다." },
      { name: "닭고기", status: "good", desc: "고단백 저지방 식품입니다(껍질 제외)." },
      { name: "오리고기", status: "caution", desc: "지방 함량이 있어 적당량만 섭취하세요." },
      { name: "양고기", status: "caution", desc: "칼로리가 있는 편이라 적당량만 섭취하세요." },
      { name: "삼겹살", status: "bad", desc: "고지방·고칼로리 부위입니다." },
      { name: "고등어", status: "good", desc: "고단백 양질의 지방을 가진 생선입니다." },
      { name: "갈치", status: "good", desc: "고단백 저칼로리 생선입니다." },
      { name: "삼치", status: "good", desc: "고단백 저칼로리 생선입니다." },
      { name: "조기", status: "good", desc: "비염장 기준 고단백 저칼로리 생선입니다." },
      { name: "명태", status: "good", desc: "고단백 저칼로리 생선입니다." },
      { name: "장어", status: "caution", desc: "지방 함량이 있는 편이라 적당량만 섭취하세요." },
      { name: "소금", status: "caution", desc: "과다 섭취 시 부종과 체중 변동을 유발할 수 있습니다." },
      { name: "고추장", status: "caution", desc: "당분과 나트륨이 있어 소량만 사용하세요." },
      { name: "식초", status: "good", desc: "저칼로리 조미료입니다." },
      { name: "후추", status: "good", desc: "저칼로리 향신료입니다." },
      { name: "참기름", status: "caution", desc: "칼로리가 높아 소량만 사용하세요." },
      { name: "들기름", status: "caution", desc: "칼로리가 높아 소량만 사용하세요." },
      { name: "고춧가루", status: "good", desc: "저칼로리 향신료입니다." },
      { name: "밀가루", status: "bad", desc: "정제 탄수화물로 칼로리가 높은 편입니다." },
      { name: "부침가루", status: "bad", desc: "기름과 탄수화물로 칼로리가 높습니다." },
      { name: "튀김가루", status: "bad", desc: "튀김옷으로 칼로리가 매우 높아집니다." },
      { name: "전분가루", status: "caution", desc: "정제 탄수화물로 칼로리가 있습니다." },
      { name: "빵가루", status: "bad", desc: "튀김옷으로 칼로리가 높아집니다." },
      { name: "코코아가루", status: "good", desc: "무가당 제품 기준 저칼로리 재료입니다." },
      { name: "단백질보충제", status: "good", desc: "고단백 저칼로리 보충 식품으로 활용할 수 있습니다." },
    ],
    stages: [
      {
        key: "general",
        label: "일반적인 체중 관리",
        guidance: "일일 섭취 칼로리를 활동량에 맞춰 약간의 적자로 유지하고, 고단백·고식이섬유 식품 위주로 구성하는 것이 좋습니다.",
        meals: [
          {
            title: "저칼로리 고단백 식단 A",
            breakfast: ["그릭요거트", "블루베리", "견과류 소량"],
            lunch: ["현미밥(소량)", "닭가슴살구이", "브로콜리찜"],
            dinner: ["두부스테이크", "시금치나물", "토마토"],
            snack: ["오이스틱"],
          },
          {
            title: "저칼로리 고단백 식단 B",
            breakfast: ["삶은 계란 2개", "사과"],
            lunch: ["현미밥(소량)", "연어구이", "채소샐러드"],
            dinner: ["두부조림", "브로콜리", "오이무침"],
            snack: ["그릭요거트"],
          },
        ],
      },
      {
        key: "overweight",
        label: "경도 비만 (BMI 25~29.9)",
        guidance: "하루 총 섭취 칼로리를 기존보다 300~500kcal 줄이고, 정제 탄수화물과 간식을 줄이는 것으로 시작하는 것이 좋습니다.",
        meals: [
          {
            title: "칼로리 조절 식단 A",
            breakfast: ["삶은 계란 2개", "방울토마토"],
            lunch: ["현미밥 2/3공기", "닭가슴살구이", "브로콜리찜"],
            dinner: ["두부조림", "시금치나물"],
            snack: ["그릭요거트"],
          },
          {
            title: "칼로리 조절 식단 B",
            breakfast: ["그릭요거트", "블루베리"],
            lunch: ["잡곡밥 2/3공기", "연어구이", "채소샐러드"],
            dinner: ["닭가슴살샐러드", "고구마 소량"],
            snack: ["오이스틱"],
          },
        ],
      },
      {
        key: "obese",
        label: "고도 비만 (BMI 30 이상)",
        guidance: "칼로리 제한과 함께 반드시 의료진의 관리 하에 식단을 조정하는 것이 안전합니다. 무리한 저칼로리 식단은 근손실과 요요를 부를 수 있습니다.",
        meals: [
          {
            title: "의료진 관리형 식단 A",
            breakfast: ["삶은 계란 2개", "오이"],
            lunch: ["닭가슴살구이", "브로콜리찜", "현미밥 1/2공기"],
            dinner: ["두부스테이크", "시금치나물"],
            snack: ["방울토마토"],
          },
          {
            title: "의료진 관리형 식단 B",
            breakfast: ["무가당 그릭요거트"],
            lunch: ["연어구이", "채소샐러드", "고구마 소량"],
            dinner: ["닭가슴살샐러드"],
            snack: ["오이스틱"],
          },
        ],
      },
    ],
  },
};

const STATUS_META = {
  good: { label: "적합", className: "status-good" },
  caution: { label: "주의", className: "status-caution" },
  bad: { label: "부적합", className: "status-bad" },
};
